#!/bin/sh

FORBIDEN_FUNC=$(cat $1.map | grep ".text.*(.*\.o)" | cut -d'(' -f2 | cut -d')' -f1 | grep -v -f $2)
if [ "x${FORBIDEN_FUNC}" != "x" ]; then
	echo "unexpected function used in $1 :"
	echo ${FORBIDEN_FUNC} | awk '{print $0}' RS=' '
	exit 1;
fi

exit 0;
